/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#e9b8d9",
        "surface-tint": "#79526f",
        "inverse-on-surface": "#f0f1f2",
        "inverse-surface": "#2e3132",
        "secondary-container": "#d6e0f1",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "tertiary-container": "#4b5d33",
        "tertiary-fixed": "#d5eab4",
        "on-background": "#191c1d",
        "on-surface": "#191c1d",
        "primary-container": "#714b67",
        "surface-variant": "#e1e3e4",
        "background": "#f8f9fa",
        "on-primary-fixed-variant": "#5f3b56",
        "on-tertiary-container": "#c0d5a0",
        "surface-container-high": "#e7e8e9",
        "secondary": "#555f6d",
        "on-secondary-fixed-variant": "#3e4755",
        "primary-fixed": "#ffd7f1",
        "on-secondary-container": "#596372",
        "on-surface-variant": "#4e444a",
        "on-primary-container": "#f0bfe0",
        "surface-container-low": "#f3f4f5",
        "primary-fixed-dim": "#e9b8d9",
        "surface": "#f8f9fa",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#bdc7d8",
        "tertiary": "#34451e",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "surface-bright": "#f8f9fa",
        "on-primary-fixed": "#2f1029",
        "error-container": "#ffdad6",
        "surface-container": "#edeeef",
        "primary": "#57344f",
        "secondary-fixed": "#d9e3f4",
        "tertiary-fixed-dim": "#b9ce9a",
        "surface-dim": "#d9dadb",
        "on-error": "#ffffff",
        "surface-container-highest": "#e1e3e4",
        "on-tertiary-fixed-variant": "#3b4c24",
        "outline": "#80747a",
        "on-secondary-fixed": "#121c28",
        "on-tertiary-fixed": "#112000",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#d1c3ca"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "navbar_height": "56px",
        "cell_padding_x": "12px",
        "gutter": "16px",
        "container_padding": "24px",
        "unit": "4px",
        "sidebar_width": "240px",
        "cell_padding_y": "8px"
      },
      fontFamily: {
        "title-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display": ["Inter", "sans-serif"],
        "code": ["JetBrains Mono", "monospace"]
      }
    },
  },
  plugins: [],
}
